apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
         app: conversao
    spec:
      containers:
        - name: conversao
          image: carlosruan/bootcamp-kubernetes-2.0-api-conversao:v1
          ports:
            - containerPort: 8080
